networks:
  sparkpg_network:

services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    container_name: minio
    networks:
      - sparkpg_network
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
          - ./minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001

  spark-master:
    build:
      context: .
      dockerfile: dockerfile.spark.new
    container_name: spark-master
    networks:
      - sparkpg_network
    volumes:
      - ./spark-events:/opt/spark/events 
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-master.sh; tail -f /dev/null"
    ports:
      - '8080:8080'
      - '4040:4040'
      - '7077:7077'

  spark-worker:
    build:
      context: .
      dockerfile: dockerfile.spark.new
    container_name: spark-worker1
    networks:
      - sparkpg_network
    volumes:
      - ./spark-events:/opt/spark/events 
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-worker.sh  spark://spark-master:7077; tail -f /dev/null"

  spark-history-server:
    build:
      context: .
      dockerfile: dockerfile.spark.new
    container_name: spark-history-server
    networks:
      - sparkpg_network
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-history-server.sh; tail -f /dev/null"
    volumes:
      - ./spark-events:/opt/spark/events 
    ports:
      - '18080:18080'  
